name: expenses
description: "expenses app for user location"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  go_router: ^13.2.2
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  dio: ^5.7.0
  get_it: ^8.0.3
  intl: ^0.20.1
  hive_flutter: ^1.1.0
  file_picker: ^10.3.1
  infinite_scroll_pagination: ^4.1.0
  hive: ^2.2.3
  flutter_screenutil: ^5.9.3
  animated_custom_dropdown: ^3.0.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  # HTTP Inspector tool for Flutter which helps debugging http requests.
  requests_inspector: ^4.2.1

flutter:
  uses-material-design: true
